### ISSUE TITLE
Lab 10 Connection Test fails

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/DP-203-Data-Engineer#203]
#### Step: 12

Description of issue: When trying to save the Synapse Output, the connection test fails with the error "Error connecting to staging blob storage for Synapse SQL pool output. The specified container does not exist"

![Screenshot 2022-12-05 at 1 07 54 PM](https://user-images.githubusercontent.com/48496971/205748157-77c1beb7-e8d2-48cc-b73f-4c5850a78d84.png)

**Comment by stevenhoward30** [comment]
I have a student having this exact same issue today.

**Comment by annav88** [comment]
workaround is adding a SQL Server output (and use the Synapse Analytics Dedicated SQL Pool endpoint)

**Comment by TheJamesHerring** [comment]
Thanks, @annav88 - I have asked for a report on North Europe and other regions to help determine this cause. I suspect the account might be getting throttled and have also reached out to the team to find out.
JH

**Comment by AMorin8787** [comment]
Not sure why this was closed, this issue is still affecting the North Europe region

**Comment by annav88** [comment]
@AMorin8787 did you try the workaround I suggested? If yes, did you manage to make it work? If not, please let me know what is blocking you

**Comment by VitalyMCT** [comment]
Are these workarounds going to flow to instructions, so the attendees and MCTs know what to do? If so, when?

**Comment by AMorin8787** [comment]
Yes the workaround allowed me to continue when I tried this morning. But the issue is also affecting the West Europe region as well

**Comment by TheJamesHerring** [comment]
@VitalyMCT When the new modules/labs are rolled out, we will re-evaluate. This particular lab is relatively new. There have been some recent changes that I'm waiting for them to settle, as I've noticed some differences in specific regions. It goes back to the objected vs. id in one of the setup scripts, which is regional but should eventually become consistent worldwide. At this point, it only affects a small portion of the training, and @annav88's workaround is excellent. We will change the primary code to reflect a consistent approach when the code is consistent globally.  HTH and Happy New Year!
JH.

**Comment by VitalyMCT** [comment]
@TheJamesHerring I appreciate your reply.

Can you please clarify the "_this particular lab is relatively new_" statement? According to GitHub it's been part of this course since its inception (Jul 21, 2021 is the exact date in version history). I've personally been teaching this lab just as long.

The present way of having MCTs go through 169 closed issues + X opened ones to try to spot various workarounds and issues that are outstanding despite being closed is just not a realistic suggestion.

Is there a reason, from a customer-experience perspective, for resistance to simply applying fixes/patches/workarounds to the instructions themselves, so customers can follow these instructions successfully A-Z? Yes, the effort on the maintenance side is surely less, however, the issue is just being offloaded to lab customers (attendees + MCTs).

It's great if the issue gets resolved in a future release, though even that sounds like it's untested. The bottom line is that **customers need to be supported, fully, on the current, live, production release of the DP-203 labs**. A key aspect of this is keeping the instructions up to date when issues are discovered in live classrooms.

**Comment by TheJamesHerring** [comment]
Apologies, @VitalyMCT, a new lab for this course will be pushed out in early H2. The only resistance to applying fixes/patches/workarounds is the publishing timeline, current workload, and ensuring that it is truly a bug in this wonderful and maturing environment that changes weekly depending upon the product.  We update instructions weekly to prevent confusion and interruption to in-flight classes. We have many cases where we changed code to fix a bug, which turned out to be a regional issue, only to change it back the following week. We absolutely value the feedback from the MCT community, and many of us are MCTs / former ATTs and only want to provide the best possible experience for all of our customers while ensuring the MCT community has the tools it needs to be successful as well.

**Comment by VitalyMCT** [comment]
@TheJamesHerring I appreciate that some issues may be regional and/or intermittent in nature. In my mind the solution approach is still the same: instruct the attendees on the steps they need to take to succeed. 

In this particular case all that needs to be done IMO is to take the workaround @annav88 suggested, i.e.:

> adding a SQL Server output (and use the Synapse Analytics Dedicated SQL Pool endpoint)

, detail it as required with steps / screenshots and add it as a note to the instructions. Markdown is great for adding notes to steps. Put in a clarification to only action the workaround if running into the issue. 

That's really the entire scope of the fix here. It would completely work around the issue until a more permanent solution is developed, or the lab is restructured, or the regional differences around this go away.

According to @AMorin8787 at least 2 regions have been impacted by this issue over a period of 3 weeks. This minor amendment would keep the course attendees and the MCTs who support them in live classrooms today on a smooth trajectory.

**Comment by TheJamesHerring** [comment]
@VitalyMCT et al. We will be deprecating this lab with a new lab on ASA in the next release which will target the simplification of the modules and associated labs without dependencies on preceding labs. The priority for all bugs in this repository has been put on hold until further notice.
