### ISSUE TITLE
UI changes in IAM

### ISSUE THREAD

**Issue by saramashfej** [MicrosoftLearning/DP-203-Data-Engineer#60]
# Module: 02
#### Step: 08

Description of issue
There has been some recent UI changes in the Identity and Access Management (IAM) tab that caused some students to be confused, can we update the screenshots in this step to reflect the new changes? Or we can add a step in the instruction to revert back to the classic UI

![image](https://user-images.githubusercontent.com/10104033/138479825-999cd5e2-85a3-4e96-b175-9d95e522a738.png)

 
Repro steps:

1. Go to Data lake
1. IAM tab
1. Add role Assignments has changed it's UI

**Comment by GraemeMalcolm** [comment]
(I'd be inclined to remove the images and use the instructions to explain at a high level what the student must do - forcing them to look at the UI and figure out how to do it. From an active learning perspective, that's a more effective way to lear; and from a content maintenance perspective, it makes the content less brittle)

**Comment by markfitzqa** [comment]
Graeme, I had delegates struggle with this.  Yes it is more active not putting the correct instructions but that is not what the delegates are paying for.

**Comment by GraemeMalcolm** [comment]
Possibly, but we also have a responsibility to help them *learn* (which isn't necessarily always easy or "enjoyable", no matter how much we want it to be) - sometimes learning requires intellectual investment on the part of the learner - especially at an advanced role-based level. Ultimately, we need to achieve a balance of getting students to think about what they're doing so that they learn effectively, vs supporting them through more complex procedures so they don;lt get completely stuck.

Also, relying less on screenshots alleviates overheads for content maintenance and localization, which is another consideration we need to think about - a high level of dependency on screenshot images makes the content more "brittle" and susceptible to (frequent) changes to the UI - especially with a product this new that's still evolving.

**Comment by markfitzqa** [comment]
The worst case is having incorrect instructions.  This needs fixing either to give them the correct screenshot and instructions or removing the incorrect instructions / screenshots and replacing with the "aim" and letting them find out how to add the role assignment for themselves.  Please do not go back to SQL 2008 days of only giving them the vague idea of what to do with no instructions though.

**Comment by GraemeMalcolm** [comment]
Agreed -there needs to be enough information there for them to complete the task.

**Comment by ctesta-oneillmsft** [comment]
Update is complete
